/**
 * In-memory cache with deduplication for gh CLI calls.
 *
 * Reduces GitHub API rate limit usage by:
 * 1. Caching responses with operation-specific TTL
 * 2. Deduplicating concurrent identical requests
 * 3. Invalidating cache after write operations
 */

interface CacheEntry<T> {
  value: T;
  expiresAt: number;
}

export class GhCache {
  private cache = new Map<string, CacheEntry<unknown>>();
  private pendingRequests = new Map<string, Promise<unknown>>();

  /**
   * TTL per operation (milliseconds)
   *
   * - prChecks: 15s - CI status changes frequently, but 15s is fast enough
   * - prView: 30s - PR metadata (title, state) changes infrequently
   * - reviewDecision: 60s - Reviews don't change often
   * - comments: 60s - Comments don't change often
   * - default: 30s - Conservative default for unknown operations
   */
  private readonly TTL = {
    prChecks: 15_000, // CI checks - frequent changes
    prView: 30_000, // PR metadata - infrequent changes
    reviewDecision: 60_000, // Reviews - rare changes
    comments: 60_000, // Comments - rare changes
    default: 30_000,
  };

  /**
   * Generate a unique cache key from gh CLI arguments.
   *
   * @example
   * key(["pr", "view", "123", "--json", "state"])
   * // Returns: "gh:pr:view:123:--json:state"
   */
  key(args: string[]): string {
    return `gh:${args.join(":")}`;
  }

  /**
   * Get TTL (time-to-live) for a specific gh operation.
   *
   * Analyzes the command structure to determine appropriate TTL.
   */
  getTTL(args: string[]): number {
    const cmd = args[0];
    if (cmd === "pr") {
      const sub = args[1];
      if (sub === "checks") return this.TTL.prChecks;
      if (sub === "view") return this.TTL.prView;
    }
    return this.TTL.default;
  }

  /**
   * Get a cached value if it exists and hasn't expired.
   *
   * @param key - Cache key generated by key()
   * @param ttlMs - TTL to check (for validation)
   * @returns Cached value or null if not found/expired
   */
  get<T>(key: string, ttlMs: number): T | null {
    const entry = this.cache.get(key);
    if (!entry) return null;

    if (Date.now() > entry.expiresAt) {
      this.cache.delete(key);
      return null;
    }

    return entry.value as T;
  }

  /**
   * Store a value in the cache with expiration.
   *
   * @param key - Cache key generated by key()
   * @param value - Value to cache
   * @param ttlMs - Time-to-live in milliseconds
   */
  set<T>(key: string, value: T, ttlMs: number): void {
    this.cache.set(key, {
      value,
      expiresAt: Date.now() + ttlMs,
    });
  }

  /**
   * Deduplicate concurrent requests for the same cache key.
   *
   * When multiple callers request the same data simultaneously,
   * only the first caller executes the API call. Subsequent callers
   * await the same Promise.
   *
   * @param key - Cache key for the request
   * @param fn - Function that performs the API call
   * @returns Result from the first execution, shared by all callers
   *
   * @example
   * // 5 agents request PR #123 simultaneously
   * // Only 1 gh CLI call is made, all 5 get the same result
   * await dedupe("gh:pr:view:123", () => gh(["pr", "view", "123"]))
   */
  async dedupe<T>(key: string, fn: () => Promise<T>): Promise<T> {
    const existing = this.pendingRequests.get(key);
    if (existing) {
      return existing as Promise<T>;
    }

    const promise = fn().finally(() => this.pendingRequests.delete(key));
    this.pendingRequests.set(key, promise);
    return promise;
  }

  /**
   * Invalidate all cache entries for a specific PR.
   *
   * Call this after write operations (merge, close, assign) to ensure
   * the cache doesn't return stale data.
   *
   * @param pr - PR to invalidate cache for
   */
  invalidatePR(pr: { owner: string; repo: string; number: number }): void {
    const repoStr = `${pr.owner}/${pr.repo}`;
    const prNumStr = `:${pr.number}:`;
    Array.from(this.cache.keys()).forEach((key) => {
      if (key.includes(repoStr) && key.includes(prNumStr)) {
        this.cache.delete(key);
      }
    });
  }

  /**
   * Invalidate all cache entries for a specific repository.
   *
   * Useful for bulk operations or webhook-driven invalidation.
   *
   * @param owner - Repository owner
   * @param repo - Repository name
   */
  invalidateRepo(owner: string, repo: string): void {
    const prefix = `gh:pr:${owner}/${repo}:`;
    Array.from(this.cache.keys()).forEach((key) => {
      if (key.includes(prefix)) {
        this.cache.delete(key);
      }
    });
  }

  /**
   * Get cache statistics for monitoring.
   *
   * @returns Current cache size and pending request count
   */
  getStats() {
    return {
      size: this.cache.size,
      pending: this.pendingRequests.size,
    };
  }

  /**
   * Clear all cached entries (useful for testing).
   */
  clear(): void {
    this.cache.clear();
    this.pendingRequests.clear();
  }
}

/** Global cache instance - singleton pattern */
export const ghCache = new GhCache();
